{ pkgs, inputs, ... }:
{
  home.packages =
    with pkgs;
    [
      alacritty
      anki
      anki-sync-server
      bc
      bottom
      calibre
      cargo
      cmake
      cmatrix
      cutter
      difftastic
      digital
      dmenu
      dos2unix
      elixir
      elixir-ls
      erlang
      expect
      fastfetch
      ffmpeg
      fzf
      gcc
      gforth
      glance
      ghidra
      graphviz
      hecate
      helix
      kitty
      lazygit
      ledger
      leetcode-cli
      libqalculate
      llvmPackages_14.clang-unwrapped
      lua
      mtr
      ncurses
      nil
      nixfmt-rfc-style
      nixd
      parallel
      (python3.withPackages (p: [
        p.flake8
        p.matplotlib
        p.pylint
        p.pyqt5
        p.python-lsp-ruff
        p.python-lsp-server
        p.qtile
      ]))
      qemu
      qownnotes
      river
      ruff
      rust-analyzer
      rustc
      rustfmt
      slides
      starship
      sway
      tclPackages.tk
      texlab
      tmux
      traceroute
      tree
      tt
      units
      verilog
      w3m
      wl-clipboard
      whois
      wmenu
      yazi
      zig
      zls
    ]
    ++ [
      inputs.ttyper.packages.x86_64-linux.default
      inputs.punctuate.packages.x86_64-linux.default
      inputs.wik.packages.x86_64-linux.default
    ];
}
