format = '''$time\[$username@$hostname\]$git_branch$nix_shell$directory
$character'''
add_newline = false

[time]
format = '\[[$time]($style)\]'

[username]
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)'

[git_branch]
format = '\([$branch]($style)\)'

[nix_shell]
format = '\([$name]($style)\)'
